/**
 * Comprehensive transpilation tests for postgresCompat and mysqlCompat.
 * Tests real and edge-case SQL patterns to find remaining inconsistencies.
 */
import { describe, it, expect } from "vitest";
import { postgresToSqlite } from "../postgresCompat";
import { mysqlToSqlite } from "../mysqlCompat";
import { transpileToSqlite, mapSqliteError, mapSqliteType, getCompatWarnings } from "../dialectCompat";

// ─── PostgreSQL Tests ────────────────────────────────────────────────────────

describe("PostgreSQL: GENERATED AS IDENTITY", () => {
  it("INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY → INTEGER PRIMARY KEY AUTOINCREMENT", () => {
    const sql = "CREATE TABLE users (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toBe("CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);");
  });

  it("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY → INTEGER PRIMARY KEY AUTOINCREMENT", () => {
    const sql = "CREATE TABLE orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, total REAL);";
    const result = postgresToSqlite(sql);
    expect(result).toBe("CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, total REAL);");
  });

  it("INT GENERATED ALWAYS AS IDENTITY (no PK) → INTEGER", () => {
    const sql = "CREATE TABLE logs (id INT GENERATED ALWAYS AS IDENTITY, message TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER");
    expect(result).not.toContain("AUTOINCREMENT");
  });
});

describe("PostgreSQL: Type mappings", () => {
  it("bare TIMESTAMP → TEXT", () => {
    const sql = "CREATE TABLE events (id INTEGER, created_at TIMESTAMP, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toBe("CREATE TABLE events (id INTEGER, created_at TEXT, name TEXT);");
  });

  it("TIMESTAMP WITH TIME ZONE → TEXT", () => {
    const sql = "CREATE TABLE events (id INTEGER, created_at TIMESTAMP WITH TIME ZONE, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toBe("CREATE TABLE events (id INTEGER, created_at TEXT, name TEXT);");
  });

  it("INT → INTEGER", () => {
    const sql = "CREATE TABLE items (id INT PRIMARY KEY, count INT, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("count INTEGER");
  });

  it("BIGINT → INTEGER", () => {
    const sql = "CREATE TABLE big (id BIGINT PRIMARY KEY, value BIGINT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("value INTEGER");
  });

  it("SMALLINT → INTEGER", () => {
    const sql = "CREATE TABLE small (id INTEGER PRIMARY KEY, code SMALLINT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("code INTEGER");
  });

  it("BOOLEAN → INTEGER", () => {
    const sql = "CREATE TABLE flags (id INTEGER PRIMARY KEY, active BOOLEAN);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("active INTEGER");
  });

  it("VARCHAR(n) → TEXT", () => {
    const sql = "CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(250), email VARCHAR(100));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("name TEXT");
    expect(result).toContain("email TEXT");
  });

  it("CHARACTER VARYING(n) → TEXT", () => {
    const sql = "CREATE TABLE users (id INTEGER PRIMARY KEY, name CHARACTER VARYING(100));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("name TEXT");
  });

  it("DOUBLE PRECISION → REAL", () => {
    const sql = "CREATE TABLE measurements (id INTEGER PRIMARY KEY, value DOUBLE PRECISION);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("value REAL");
  });

  it("SERIAL → INTEGER", () => {
    const sql = "CREATE TABLE items (id SERIAL PRIMARY KEY, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
  });

  it("TIMESTAMPTZ → TEXT", () => {
    const sql = "CREATE TABLE events (id INTEGER PRIMARY KEY, ts TIMESTAMPTZ);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("ts TEXT");
  });

  it("INT DEFAULT NEXTVAL → INTEGER NOT NULL", () => {
    const sql = "CREATE TABLE items (id INT DEFAULT NEXTVAL('items_id_seq') NOT NULL, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER NOT NULL");
    expect(result).not.toContain("NEXTVAL");
  });
});

describe("PostgreSQL: DEFAULT CURRENT_TIMESTAMP protection", () => {
  it("DEFAULT CURRENT_TIMESTAMP is preserved (not converted to DATETIME('now'))", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY, created_at TEXT DEFAULT CURRENT_TIMESTAMP);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("DEFAULT DATETIME('now')");
  });

  it("DEFAULT CURRENT_TIMESTAMP() is preserved", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY, created_at TEXT DEFAULT CURRENT_TIMESTAMP());";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("DEFAULT DATETIME('now')");
  });

  it("NOW() in SELECT is still converted to DATETIME('now')", () => {
    const sql = "SELECT NOW(), created_at FROM logs;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DATETIME('now')");
  });

  it("CURRENT_TIMESTAMP in WHERE clause is converted to DATETIME('now')", () => {
    const sql = "SELECT * FROM logs WHERE created_at > CURRENT_TIMESTAMP;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DATETIME('now')");
  });

  it("Mixed: DEFAULT CURRENT_TIMESTAMP preserved + NOW() converted", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY, created_at TEXT DEFAULT CURRENT_TIMESTAMP, count INTEGER DEFAULT 0);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).toContain("DEFAULT 0");
  });

  it("TIMESTAMP DEFAULT CURRENT_TIMESTAMP → TEXT DEFAULT CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("name TEXT");
    expect(result).toContain("created_at TEXT DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("DATETIME('now')");
  });
});

describe("PostgreSQL: Other transformations", () => {
  it("TRUE/FALSE → 1/0", () => {
    const sql = "SELECT * FROM flags WHERE active = TRUE AND deleted = FALSE;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("= 1");
    expect(result).toContain("= 0");
  });

  it("TRUNCATE TABLE → DELETE FROM", () => {
    const sql = "TRUNCATE TABLE users;";
    expect(postgresToSqlite(sql)).toBe("DELETE FROM users;");
  });

  it("ILIKE → LOWER LIKE", () => {
    const sql = "SELECT * FROM users WHERE name ILIKE '%john%';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(name) LIKE LOWER('%john%')");
  });

  it("::type CAST → CAST(expr AS type)", () => {
    const sql = "SELECT id::TEXT FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(id AS TEXT)");
  });

  it("RETURNING * removed", () => {
    const sql = "INSERT INTO users (name) VALUES ('John') RETURNING *;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("RETURNING");
  });

  it("EXTRACT(YEAR FROM date) → strftime", () => {
    const sql = "SELECT EXTRACT(YEAR FROM created_at) FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("strftime('%Y'");
  });

  it("ON CONFLICT DO NOTHING → INSERT OR IGNORE", () => {
    const sql = "INSERT INTO users (id, name) VALUES (1, 'John') ON CONFLICT DO NOTHING;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("INSERT OR IGNORE");
  });

  it("ON CONFLICT DO UPDATE → INSERT OR REPLACE", () => {
    const sql = "INSERT INTO users (id, name) VALUES (1, 'John') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("INSERT OR REPLACE");
    expect(result).not.toContain("ON CONFLICT");
    expect(result).not.toContain("EXCLUDED");
  });
});

// ─── MySQL Tests ────────────────────────────────────────────────────────────

describe("MySQL: DEFAULT CURRENT_TIMESTAMP protection", () => {
  it("DEFAULT CURRENT_TIMESTAMP is preserved", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("DEFAULT DATETIME('now')");
  });

  it("DEFAULT CURRENT_TIMESTAMP() is preserved", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP());";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("DEFAULT DATETIME('now')");
  });

  it("ON UPDATE CURRENT_TIMESTAMP is removed", () => {
    const sql = "CREATE TABLE logs (id INT AUTO_INCREMENT PRIMARY KEY, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("ON UPDATE");
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
  });

  it("NOW() in SELECT → DATETIME('now')", () => {
    const sql = "SELECT NOW(), name FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DATETIME('now')");
  });

  it("CURRENT_TIMESTAMP() in SELECT → DATETIME('now')", () => {
    const sql = "SELECT CURRENT_TIMESTAMP(), name FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DATETIME('now')");
  });

  it("Mixed: DEFAULT CURRENT_TIMESTAMP preserved + DATETIME → TEXT", () => {
    const sql = "CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), created_at DATETIME DEFAULT CURRENT_TIMESTAMP);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("name TEXT");
    expect(result).toContain("created_at TEXT DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("DATETIME('now')");
  });
});

describe("MySQL: TRUE/FALSE → 1/0", () => {
  it("TRUE → 1 in WHERE", () => {
    const sql = "SELECT * FROM users WHERE active = TRUE;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("= 1");
  });

  it("FALSE → 0 in WHERE", () => {
    const sql = "SELECT * FROM users WHERE deleted = FALSE;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("= 0");
  });

  it("TRUE/FALSE in INSERT", () => {
    const sql = "INSERT INTO flags (active, deleted) VALUES (TRUE, FALSE);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("VALUES (1, 0)");
  });
});

describe("MySQL: Type mappings", () => {
  it("BOOLEAN → INTEGER", () => {
    const sql = "CREATE TABLE flags (id INT PRIMARY KEY, active BOOLEAN);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("active INTEGER");
  });

  it("DATETIME → TEXT", () => {
    const sql = "CREATE TABLE events (id INT PRIMARY KEY, created_at DATETIME);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("created_at TEXT");
  });

  it("INT → INTEGER", () => {
    const sql = "CREATE TABLE items (id INT PRIMARY KEY, count INT);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("count INTEGER");
  });

  it("INT(11) → INTEGER", () => {
    const sql = "CREATE TABLE users (id INT(11) PRIMARY KEY, name VARCHAR(100));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("name TEXT");
  });

  it("TINYINT(1) → INTEGER", () => {
    const sql = "CREATE TABLE items (id INT PRIMARY KEY, flag TINYINT(1));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("flag INTEGER");
  });

  it("BIGINT(20) → INTEGER", () => {
    const sql = "CREATE TABLE big (id BIGINT PRIMARY KEY, value BIGINT(20));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("value INTEGER");
  });

  it("SMALLINT(5) → INTEGER", () => {
    const sql = "CREATE TABLE items (id INT PRIMARY KEY, code SMALLINT(5));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("code INTEGER");
  });

  it("MEDIUMINT(7) → INTEGER", () => {
    const sql = "CREATE TABLE items (id INT PRIMARY KEY, status MEDIUMINT(7));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("status INTEGER");
  });

  it("DOUBLE → REAL", () => {
    const sql = "CREATE TABLE measurements (id INT PRIMARY KEY, value DOUBLE);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("value REAL");
  });

  it("FLOAT → REAL", () => {
    const sql = "CREATE TABLE measurements (id INT PRIMARY KEY, value FLOAT);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("value REAL");
  });

  it("DECIMAL(10,2) → REAL", () => {
    const sql = "CREATE TABLE products (id INT PRIMARY KEY, price DECIMAL(10,2));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("price REAL");
  });

  it("AUTO_INCREMENT → AUTOINCREMENT", () => {
    const sql = "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INTEGER PRIMARY KEY AUTOINCREMENT");
  });

  it("INT(11) NOT NULL AUTO_INCREMENT → INTEGER NOT NULL AUTOINCREMENT", () => {
    const sql = "CREATE TABLE users (id INT(11) NOT NULL AUTO_INCREMENT, name VARCHAR(100), PRIMARY KEY (id));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INTEGER NOT NULL AUTOINCREMENT");
    expect(result).toContain("PRIMARY KEY");
  });
});

describe("MySQL: Other transformations", () => {
  it("Backticks → Double quotes", () => {
    const sql = "SELECT `name`, `id` FROM `users`;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('"name"');
    expect(result).toContain('"users"');
  });

  it("RIGHT JOIN → LEFT JOIN swapped", () => {
    const sql = "SELECT * FROM orders RIGHT JOIN customers ON orders.customer_id = customers.id;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("LEFT JOIN");
    expect(result).not.toContain("RIGHT JOIN");
  });

  it("LIMIT x, y → LIMIT y OFFSET x", () => {
    const sql = "SELECT * FROM users LIMIT 10, 20;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("LIMIT 20 OFFSET 10");
  });

  it("IF(expr, a, b) → CASE WHEN", () => {
    const sql = "SELECT IF(active, 'yes', 'no') FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CASE WHEN");
  });

  it("CONCAT(a, b) → a || b", () => {
    const sql = "SELECT CONCAT(first_name, ' ', last_name) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("||");
  });

  it("TRUNCATE TABLE → DELETE FROM", () => {
    const sql = "TRUNCATE TABLE users;";
    expect(mysqlToSqlite(sql)).toBe("DELETE FROM users;");
  });

  it("SHOW TABLES → sqlite_master query", () => {
    const sql = "SHOW TABLES;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("sqlite_master");
  });

  it("DESCRIBE table → PRAGMA table_info", () => {
    const sql = "DESCRIBE users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("PRAGMA table_info");
  });

  it("ON DUPLICATE KEY UPDATE → INSERT OR REPLACE", () => {
    const sql = "INSERT INTO users (id, name) VALUES (1, 'John') ON DUPLICATE KEY UPDATE name = 'John';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INSERT OR REPLACE");
  });

  it("UNSIGNED removed", () => {
    const sql = "CREATE TABLE items (id INT UNSIGNED PRIMARY KEY, value BIGINT UNSIGNED);";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("UNSIGNED");
  });

  it("YEAR() → strftime", () => {
    const sql = "SELECT YEAR(created_at) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("strftime('%Y'");
  });

  it("MONTH() → strftime", () => {
    const sql = "SELECT MONTH(created_at) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("strftime('%m'");
  });

  it("CURDATE() → DATE('now')", () => {
    const sql = "SELECT CURDATE();";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DATE('now')");
  });

  it("DATEDIFF → julianday", () => {
    const sql = "SELECT DATEDIFF('2024-01-10', '2024-01-01') AS diff;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("julianday");
  });

  it("SUBSTRING → SUBSTR", () => {
    const sql = "SELECT SUBSTRING(name, 1, 5) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("SUBSTR");
  });

  it("SET SQL_MODE removed", () => {
    const sql = "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO'; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("SET SQL_MODE");
    expect(result).toContain("SELECT * FROM users");
  });

  it("phpMyAdmin version comments removed", () => {
    const sql = "/*!40101 SET NAMES utf8 */; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("40101");
  });

  it("ENGINE=InnoDB removed", () => {
    const sql = "CREATE TABLE users (id INT PRIMARY KEY, name VARCHAR(100)) ENGINE=InnoDB;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("ENGINE");
  });
});

// ─── Cross-dialect edge cases ────────────────────────────────────────────────

describe("Cross-dialect edge cases", () => {
  it("PG: Multiple TIMESTAMP columns (bare + WITH TIME ZONE)", () => {
    const sql = "CREATE TABLE events (id INTEGER PRIMARY KEY, created_at TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("created_at TEXT");
    expect(result).toContain("updated_at TEXT");
  });

  it("PG: Multiple defaults including CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY, created_at TEXT DEFAULT CURRENT_TIMESTAMP, count INTEGER DEFAULT 0);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).toContain("DEFAULT 0");
  });

  it("MySQL: DEFAULT CURRENT_TIMESTAMP + ON UPDATE CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE logs (id INT AUTO_INCREMENT PRIMARY KEY, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).not.toContain("ON UPDATE");
    expect(result).not.toContain("DATETIME('now')");
  });

  it("MySQL: CURRENT_TIMESTAMP in WHERE (not DEFAULT) should be converted", () => {
    const sql = "SELECT * FROM logs WHERE created_at > CURRENT_TIMESTAMP;";
    const result = mysqlToSqlite(sql);
    // CURRENT_TIMESTAMP without parens in WHERE — mysqlCompat should convert it
    expect(result).toContain("DATETIME('now')");
  });
});

// ─── String Literal Safety Tests ────────────────────────────────────────────

describe("String literal safety: TRUE/FALSE inside strings", () => {
  it("PG: TRUE inside string literal should NOT be converted", () => {
    const sql = "SELECT name FROM patients WHERE insured = 'true';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'true'");
    expect(result).not.toContain("'1'");
  });

  it("PG: FALSE inside string literal should NOT be converted", () => {
    const sql = "SELECT name FROM patients WHERE insured = 'false';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'false'");
    expect(result).not.toContain("'0'");
  });

  it("MySQL: TRUE inside string literal should NOT be converted", () => {
    const sql = "SELECT name FROM patients WHERE insured = 'true';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'true'");
    expect(result).not.toContain("'1'");
  });

  it("MySQL: FALSE inside string literal should NOT be converted", () => {
    const sql = "SELECT name FROM patients WHERE insured = 'false';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'false'");
    expect(result).not.toContain("'0'");
  });

  it("PG: TRUE keyword outside strings should be converted", () => {
    const sql = "SELECT * FROM t WHERE active = TRUE;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("= 1");
  });

  it("MySQL: TRUE keyword outside strings should be converted", () => {
    const sql = "SELECT * FROM t WHERE active = TRUE;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("= 1");
  });

  it("PG: Mixed — string 'true' vs keyword TRUE", () => {
    const sql = "SELECT * FROM t WHERE name = 'true' AND active = TRUE;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'true'");
    expect(result).toContain("= 1");
  });

  it("MySQL: Mixed — string 'true' vs keyword TRUE", () => {
    const sql = "SELECT * FROM t WHERE name = 'true' AND active = TRUE;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'true'");
    expect(result).toContain("= 1");
  });
});

// ─── Type Keyword Safety Tests ──────────────────────────────────────────────

describe("Type keyword safety: INT etc. inside strings/column names", () => {
  it("PG: INT inside column name should NOT be converted", () => {
    // Column name "international" contains "int" but should not be affected
    const sql = "SELECT international FROM countries;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("international");
  });

  it("MySQL: INT inside column name should NOT be converted", () => {
    const sql = "SELECT international FROM countries;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("international");
  });

  it("PG: TIMESTAMP inside string literal should NOT be converted", () => {
    const sql = "SELECT 'TIMESTAMP' AS type_name;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'TIMESTAMP'");
  });

  it("MySQL: DATETIME inside string literal should NOT be converted", () => {
    const sql = "SELECT 'DATETIME' AS type_name;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'DATETIME'");
  });
});

// ─── Multi-statement edge cases ─────────────────────────────────────────────

describe("Multi-statement edge cases", () => {
  it("PG: Multiple statements with mixed CURRENT_TIMESTAMP usage", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY, ts TEXT DEFAULT CURRENT_TIMESTAMP); SELECT * FROM logs WHERE ts > CURRENT_TIMESTAMP;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    // The second CURRENT_TIMESTAMP in WHERE should be converted
    expect(result).toContain("DATETIME('now')");
  });

  it("MySQL: Multiple statements with mixed CURRENT_TIMESTAMP usage", () => {
    const sql = "CREATE TABLE logs (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT DEFAULT CURRENT_TIMESTAMP); SELECT * FROM logs WHERE ts > CURRENT_TIMESTAMP();";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
    expect(result).toContain("DATETIME('now')");
  });

  it("PG: CREATE TABLE with SERIAL + VARCHAR + TIMESTAMP DEFAULT CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, active BOOLEAN DEFAULT TRUE);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("name TEXT");
    expect(result).toContain("created_at TEXT DEFAULT CURRENT_TIMESTAMP");
    expect(result).toContain("active INTEGER DEFAULT 1");
    expect(result).not.toContain("DATETIME('now')");
  });

  it("MySQL: CREATE TABLE with INT AUTO_INCREMENT + VARCHAR + DATETIME DEFAULT CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, active BOOLEAN DEFAULT TRUE);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(result).toContain("name TEXT");
    expect(result).toContain("created_at TEXT DEFAULT CURRENT_TIMESTAMP");
    expect(result).toContain("active INTEGER DEFAULT 1");
    expect(result).not.toContain("DATETIME('now')");
  });
});

// ─── Real dataset SQL patterns ──────────────────────────────────────────────

describe("Real dataset SQL patterns", () => {
  it("PG: Typical banking table", () => {
    const sql = "CREATE TABLE kunden (id SERIAL PRIMARY KEY, name VARCHAR(100), geburtsdatum DATE, adresse VARCHAR(200), registriert_am DATE);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("name TEXT");
    expect(result).toContain("adresse TEXT");
  });

  it("MySQL: Typical banking table", () => {
    const sql = "CREATE TABLE kunden (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), geburtsdatum DATE, adresse VARCHAR(200), registriert_am DATE);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(result).toContain("name TEXT");
    expect(result).toContain("adresse TEXT");
  });

  it("PG: Table with BOOLEAN + TIMESTAMP DEFAULT CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE patienten (id SERIAL PRIMARY KEY, name VARCHAR(100), versichert BOOLEAN DEFAULT TRUE, erstellt_am TIMESTAMP DEFAULT CURRENT_TIMESTAMP);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("name TEXT");
    expect(result).toContain("versichert INTEGER DEFAULT 1");
    expect(result).toContain("erstellt_am TEXT DEFAULT CURRENT_TIMESTAMP");
  });

  it("MySQL: Table with BOOLEAN + DATETIME DEFAULT CURRENT_TIMESTAMP", () => {
    const sql = "CREATE TABLE patienten (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), versichert BOOLEAN DEFAULT TRUE, erstellt_am DATETIME DEFAULT CURRENT_TIMESTAMP);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(result).toContain("name TEXT");
    expect(result).toContain("versichert INTEGER DEFAULT 1");
    expect(result).toContain("erstellt_am TEXT DEFAULT CURRENT_TIMESTAMP");
  });

  it("PG: SELECT with NOW() + ILIKE", () => {
    const sql = "SELECT * FROM users WHERE name ILIKE '%john%' AND created_at > NOW();";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(name) LIKE LOWER('%john%')");
    expect(result).toContain("DATETIME('now')");
  });

  it("MySQL: SELECT with NOW() + LIMIT offset", () => {
    const sql = "SELECT * FROM users WHERE name LIKE '%john%' AND created_at > NOW() LIMIT 10, 20;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DATETIME('now')");
    expect(result).toContain("LIMIT 20 OFFSET 10");
  });
});

// ─── Advanced Edge Cases ────────────────────────────────────────────────────

describe("Advanced edge cases: RETURNING variants", () => {
  it("PG: RETURNING * is removed", () => {
    const sql = "INSERT INTO users (name) VALUES ('John') RETURNING *;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("RETURNING");
  });

  it("PG: RETURNING id, name is removed", () => {
    const sql = "INSERT INTO users (name) VALUES ('John') RETURNING id, name;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("RETURNING");
  });
});

describe("Advanced edge cases: ILIKE variants", () => {
  it("PG: ILIKE with table-qualified column", () => {
    const sql = "SELECT * FROM users WHERE u.name ILIKE '%john%';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(u.name) LIKE LOWER('%john%')");
  });

  it("PG: ILIKE with multiple conditions", () => {
    const sql = "SELECT * FROM users WHERE name ILIKE '%john%' AND age > 18;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(name) LIKE LOWER('%john%')");
    expect(result).toContain("age > 18");
  });
});

describe("PG: IS DISTINCT FROM / IS NOT DISTINCT FROM", () => {
  it("IS DISTINCT FROM → IS NOT", () => {
    const sql = "SELECT * FROM users WHERE status IS DISTINCT FROM 'active';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("status IS NOT 'active'");
    expect(result).not.toContain("DISTINCT");
  });

  it("IS NOT DISTINCT FROM → IS", () => {
    const sql = "SELECT * FROM users WHERE status IS NOT DISTINCT FROM 'active';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("status IS 'active'");
    expect(result).not.toContain("DISTINCT");
  });

  it("IS DISTINCT FROM with column reference", () => {
    const sql = "SELECT * FROM t WHERE a IS DISTINCT FROM b;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("a IS NOT b");
  });

  it("IS NOT DISTINCT FROM with table-qualified column", () => {
    const sql = "SELECT * FROM t WHERE t.id IS NOT DISTINCT FROM u.id;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("t.id IS u.id");
  });
});

describe("Advanced edge cases: ALTER TABLE ADD COLUMN", () => {
  it("PG: ALTER TABLE ADD COLUMN with VARCHAR → TEXT", () => {
    const sql = "ALTER TABLE users ADD COLUMN email VARCHAR(100);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("email TEXT");
  });

  it("PG: ALTER TABLE ADD COLUMN with TIMESTAMP DEFAULT CURRENT_TIMESTAMP", () => {
    const sql = "ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("created_at TEXT DEFAULT CURRENT_TIMESTAMP");
  });

  it("PG: ALTER TABLE ADD COLUMN with BOOLEAN DEFAULT TRUE", () => {
    const sql = "ALTER TABLE users ADD COLUMN active BOOLEAN DEFAULT TRUE;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("active INTEGER DEFAULT 1");
  });

  it("PG: ALTER TABLE ADD COLUMN with INT → INTEGER", () => {
    const sql = "ALTER TABLE users ADD COLUMN count INT DEFAULT 0;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("count INTEGER DEFAULT 0");
  });

  it("MySQL: ALTER TABLE ADD COLUMN with VARCHAR → TEXT (known limitation: no type conversion in ALTER TABLE)", () => {
    // MySQL's transformAlterTable doesn't convert types in ADD COLUMN
    // This is a known limitation — ALTER TABLE ADD COLUMN type conversion
    // only works for PG, not for MySQL
    const sql = "ALTER TABLE users ADD COLUMN email VARCHAR(100);";
    const result = mysqlToSqlite(sql);
    // MySQL ALTER TABLE doesn't convert types — VARCHAR stays as-is
    expect(result).toContain("VARCHAR(100)");
  });

  it("MySQL: ALTER TABLE ADD COLUMN with BOOLEAN DEFAULT TRUE (known limitation)", () => {
    const sql = "ALTER TABLE users ADD COLUMN active BOOLEAN DEFAULT TRUE;";
    const result = mysqlToSqlite(sql);
    // MySQL ALTER TABLE doesn't convert BOOLEAN or TRUE
    expect(result).toContain("BOOLEAN");
    expect(result).toContain("DEFAULT 1"); // TRUE → 1 still works via transformBooleans
  });
});

describe("Advanced edge cases: Multi-statement SQL", () => {
  it("PG: CREATE TABLE + INSERT in one string", () => {
    const sql = "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100)); INSERT INTO users (name) VALUES ('John');";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("name TEXT");
    expect(result).toContain("INSERT INTO users");
  });

  it("MySQL: CREATE TABLE + INSERT in one string", () => {
    const sql = "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100)); INSERT INTO users (name) VALUES ('John');";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(result).toContain("name TEXT");
    expect(result).toContain("INSERT INTO users");
  });

  it("PG: INSERT with TRUE/FALSE values", () => {
    const sql = "INSERT INTO flags (name, active) VALUES ('test', TRUE);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'test'");
    expect(result).toContain("1");
  });

  it("MySQL: INSERT with TRUE/FALSE values", () => {
    const sql = "INSERT INTO flags (name, active) VALUES ('test', TRUE);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'test'");
    expect(result).toContain("1");
  });
});

describe("Advanced edge cases: String literal safety for type keywords", () => {
  it("PG: VARCHAR inside string literal should NOT be converted", () => {
    const sql = "SELECT 'VARCHAR is a type' AS info;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'VARCHAR is a type'");
  });

  it("MySQL: INT inside string literal should NOT be converted", () => {
    const sql = "SELECT 'INT is a type' AS info;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'INT is a type'");
  });

  it("PG: TIMESTAMP inside string literal should NOT be converted", () => {
    const sql = "SELECT 'TIMESTAMP value' AS info;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'TIMESTAMP value'");
  });

  it("MySQL: DATETIME inside string literal should NOT be converted", () => {
    const sql = "SELECT 'DATETIME value' AS info;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'DATETIME value'");
  });

  it("PG: BOOLEAN inside string literal should NOT be converted", () => {
    const sql = "SELECT 'BOOLEAN' AS type_name;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'BOOLEAN'");
  });

  it("PG: NOW() inside string literal should NOT be converted", () => {
    const sql = "SELECT 'Use NOW() for current time' AS tip;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'Use NOW() for current time'");
    expect(result).not.toContain("DATETIME('now') for current time");
  });

  it("MySQL: NOW() inside string literal should NOT be converted", () => {
    const sql = "SELECT 'Use NOW() for current time' AS tip;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'Use NOW() for current time'");
    expect(result).not.toContain("DATETIME('now') for current time");
  });

  it("PG: DEFAULT string with 'true' should NOT be converted to '1'", () => {
    const sql = "CREATE TABLE t (id INTEGER PRIMARY KEY, status TEXT DEFAULT 'true');";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT 'true'");
    expect(result).not.toContain("DEFAULT '1'");
  });

  it("MySQL: DEFAULT string with 'true' should NOT be converted to '1'", () => {
    const sql = "CREATE TABLE t (id INT PRIMARY KEY, status VARCHAR(20) DEFAULT 'true');";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DEFAULT 'true'");
    expect(result).not.toContain("DEFAULT '1'");
  });
});

describe("Advanced edge cases: Complex CREATE TABLE patterns", () => {
  it("PG: CREATE TABLE with composite PRIMARY KEY", () => {
    const sql = "CREATE TABLE film_schauspieler (film_id INTEGER REFERENCES filme(id), schauspieler_id INTEGER REFERENCES schauspieler(id), PRIMARY KEY (film_id, schauspieler_id));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("PRIMARY KEY (film_id, schauspieler_id)");
    expect(result).toContain("REFERENCES filme(id)");
  });

  it("MySQL: CREATE TABLE with composite PRIMARY KEY", () => {
    const sql = "CREATE TABLE film_schauspieler (film_id INTEGER REFERENCES filme(id), schauspieler_id INTEGER REFERENCES schauspieler(id), PRIMARY KEY (film_id, schauspieler_id));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("PRIMARY KEY (film_id, schauspieler_id)");
  });

  it("PG: CREATE TABLE with CHECK constraint", () => {
    const sql = "CREATE TABLE bewertungen (id INTEGER PRIMARY KEY, sterne INTEGER NOT NULL CHECK(sterne BETWEEN 1 AND 5));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CHECK(sterne BETWEEN 1 AND 5)");
  });

  it("PG: CREATE TABLE with DEFAULT string value", () => {
    const sql = "CREATE TABLE tickets (id SERIAL PRIMARY KEY, status TEXT DEFAULT 'offen');";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DEFAULT 'offen'");
  });

  it("MySQL: CREATE TABLE with DEFAULT string value", () => {
    const sql = "CREATE TABLE tickets (id INT AUTO_INCREMENT PRIMARY KEY, status VARCHAR(20) DEFAULT 'offen');";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DEFAULT 'offen'");
    expect(result).toContain("status TEXT");
  });

  it("PG: CREATE TABLE with nullable REFERENCES", () => {
    const sql = "CREATE TABLE mitarbeiter (id SERIAL PRIMARY KEY, name VARCHAR(100), manager_id INTEGER REFERENCES mitarbeiter(id));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
    expect(result).toContain("name TEXT");
    expect(result).toContain("manager_id INTEGER REFERENCES mitarbeiter(id)");
  });

  it("MySQL: CREATE TABLE with nullable REFERENCES", () => {
    const sql = "CREATE TABLE mitarbeiter (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), manager_id INT REFERENCES mitarbeiter(id));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(result).toContain("name TEXT");
    expect(result).toContain("manager_id INTEGER REFERENCES mitarbeiter(id)");
  });

  it("PG: CREATE TABLE with UNIQUE constraint", () => {
    const sql = "CREATE TABLE codes (id INTEGER PRIMARY KEY, code TEXT UNIQUE NOT NULL);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("UNIQUE NOT NULL");
  });
});

describe("Advanced edge cases: DECIMAL and numeric types", () => {
  it("PG: DECIMAL(10,2) → REAL", () => {
    const sql = "CREATE TABLE products (id SERIAL PRIMARY KEY, price DECIMAL(10,2));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("price REAL");
  });

  it("PG: NUMERIC(10,2) → REAL", () => {
    const sql = "CREATE TABLE products (id SERIAL PRIMARY KEY, price NUMERIC(10,2));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("price REAL");
  });

  it("MySQL: DECIMAL(10,2) → REAL", () => {
    const sql = "CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, price DECIMAL(10,2));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("price REAL");
  });

  it("MySQL: NUMERIC(10,2) → REAL", () => {
    const sql = "CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, price NUMERIC(10,2));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("price REAL");
  });
});

describe("Advanced edge cases: Dollar-quoted strings (PG)", () => {
  it("PG: $$...$$ → single-quoted string", () => {
    const sql = "SELECT $$hello world$$;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'hello world'");
  });

  it("PG: $tag$...$tag$ → single-quoted string", () => {
    const sql = "SELECT $tag$hello world$tag$;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'hello world'");
  });
});

describe("Advanced edge cases: CAST shorthand (PG)", () => {
  it("PG: ::text → CAST(expr AS TEXT)", () => {
    const sql = "SELECT id::text FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(id AS TEXT)");
  });

  it("PG: ::integer → CAST(expr AS INTEGER)", () => {
    const sql = "SELECT price::integer FROM products;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(price AS INTEGER)");
  });

  it("PG: ::date → CAST(expr AS TEXT) (SQLite has no DATE type)", () => {
    const sql = "SELECT created_at::date FROM orders;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(created_at AS TEXT)");
  });
});

describe("Advanced edge cases: Window functions (pass-through)", () => {
  it("PG: ROW_NUMBER() OVER passes through", () => {
    const sql = "SELECT ROW_NUMBER() OVER (ORDER BY score DESC) AS rank FROM students;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("ROW_NUMBER() OVER");
  });

  it("MySQL: ROW_NUMBER() OVER passes through", () => {
    const sql = "SELECT ROW_NUMBER() OVER (ORDER BY score DESC) AS rank FROM students;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ROW_NUMBER() OVER");
  });

  it("PG: LAG() OVER passes through", () => {
    const sql = "SELECT LAG(price, 1) OVER (ORDER BY date) FROM stocks;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LAG(price, 1) OVER");
  });
});

describe("Advanced edge cases: CTEs (WITH)", () => {
  it("PG: CTE with TRUE → 1", () => {
    const sql = "WITH top_users AS (SELECT id, name FROM users WHERE active = TRUE) SELECT * FROM top_users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("WITH top_users AS");
    expect(result).toContain("= 1");
  });

  it("MySQL: CTE with TRUE → 1", () => {
    const sql = "WITH top_users AS (SELECT id, name FROM users WHERE active = TRUE) SELECT * FROM top_users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("WITH top_users AS");
    expect(result).toContain("= 1");
  });
});

describe("Advanced edge cases: NULL handling (pass-through)", () => {
  it("PG: IS NULL passes through", () => {
    const sql = "SELECT * FROM users WHERE manager_id IS NULL;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("IS NULL");
  });

  it("MySQL: IS NOT NULL passes through", () => {
    const sql = "SELECT * FROM users WHERE manager_id IS NOT NULL;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("IS NOT NULL");
  });
});

describe("Advanced edge cases: COALESCE (pass-through)", () => {
  it("PG: COALESCE passes through", () => {
    const sql = "SELECT COALESCE(manager_id, 0) FROM employees;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("COALESCE(manager_id, 0)");
  });

  it("MySQL: COALESCE passes through", () => {
    const sql = "SELECT COALESCE(manager_id, 0) FROM employees;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("COALESCE(manager_id, 0)");
  });
});

describe("Advanced edge cases: String concatenation (pass-through)", () => {
  it("PG: || concatenation passes through", () => {
    const sql = "SELECT 'Kopie von ' || name FROM projects;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("'Kopie von ' || name");
  });

  it("MySQL: || concatenation passes through", () => {
    const sql = "SELECT 'Kopie von ' || name FROM projects;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("'Kopie von ' || name");
  });
});

// ─── Systematic Gap Coverage ────────────────────────────────────────────────

describe("PG: CURRENT_DATE / CURRENT_TIME", () => {
  it("CURRENT_DATE → DATE('now')", () => {
    const sql = "SELECT CURRENT_DATE;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("DATE('now')");
  });

  it("CURRENT_TIME → TIME('now')", () => {
    const sql = "SELECT CURRENT_TIME;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("TIME('now')");
  });
});

describe("PG: AGE() function", () => {
  it("AGE(date1, date2) → julianday difference", () => {
    const sql = "SELECT AGE('2024-01-01', '2023-01-01') AS diff;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("julianday('2024-01-01') - julianday('2023-01-01')");
  });
});

describe("PG: DATE_TRUNC() function", () => {
  it("DATE_TRUNC('year', date) → strftime('%Y-01-01', date)", () => {
    const sql = "SELECT DATE_TRUNC('year', created_at) FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("strftime('%Y-01-01', created_at)");
  });

  it("DATE_TRUNC('month', date) → strftime('%Y-%m-01', date)", () => {
    const sql = "SELECT DATE_TRUNC('month', created_at) FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("strftime('%Y-%m-01', created_at)");
  });

  it("DATE_TRUNC('day', date) → strftime('%Y-%m-%d', date)", () => {
    const sql = "SELECT DATE_TRUNC('day', created_at) FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("strftime('%Y-%m-%d', created_at)");
  });
});

describe("PG: STRING_AGG → GROUP_CONCAT", () => {
  it("STRING_AGG(name, ', ') → GROUP_CONCAT(name, ', ')", () => {
    const sql = "SELECT STRING_AGG(name, ', ') FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("GROUP_CONCAT(name, ', ')");
    expect(result).not.toContain("STRING_AGG");
  });

  it("STRING_AGG with column and delimiter", () => {
    const sql = "SELECT STRING_AGG(email, '; ') FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("GROUP_CONCAT(email, '; ')");
  });
});

describe("PG: FILTER (WHERE) on aggregates", () => {
  it("COUNT(*) FILTER (WHERE cond) → SUM(CASE WHEN cond THEN 1 ELSE 0 END)", () => {
    const sql = "SELECT COUNT(*) FILTER (WHERE status = 'active') FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("SUM(CASE WHEN status = 'active' THEN 1 ELSE 0 END)");
    expect(result).not.toContain("FILTER");
  });

  it("SUM(x) FILTER (Where cond) → SUM(CASE WHEN cond THEN x ELSE NULL END)", () => {
    const sql = "SELECT SUM(price) FILTER (WHERE category = 'A') FROM products;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("SUM(CASE WHEN category = 'A' THEN price ELSE NULL END)");
    expect(result).not.toContain("FILTER");
  });

  it("AVG(x) FILTER (Where cond) → AVG(CASE WHEN cond THEN x ELSE NULL END)", () => {
    const sql = "SELECT AVG(score) FILTER (WHERE passed = TRUE) FROM students;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("AVG(CASE WHEN passed = 1 THEN score ELSE NULL END)");
  });
});

describe("PG: TO_CHAR / TO_NUMBER / TO_DATE", () => {
  it("TO_CHAR(date, 'YYYY-MM-DD') → strftime('%Y-%m-%d', date)", () => {
    const sql = "SELECT TO_CHAR(created_at, 'YYYY-MM-DD') FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("strftime('%Y-%m-%d', created_at)");
    expect(result).not.toContain("TO_CHAR");
  });

  it("TO_CHAR(date, 'DD.MM.YYYY') → strftime('%d.%m.%Y', date)", () => {
    const sql = "SELECT TO_CHAR(created_at, 'DD.MM.YYYY') FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("strftime('%d.%m.%Y', created_at)");
  });

  it("TO_NUMBER(expr) → CAST(expr AS INTEGER)", () => {
    const sql = "SELECT TO_NUMBER(price) FROM products;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(price AS INTEGER)");
    expect(result).not.toContain("TO_NUMBER");
  });

  it("TO_DATE(expr, 'YYYY-MM-DD') → date(expr)", () => {
    const sql = "SELECT TO_DATE('2024-01-01', 'YYYY-MM-DD') FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("date(");
    expect(result).not.toContain("TO_DATE");
  });
});

describe("PG: EXTRACT edge cases", () => {
  it("EXTRACT(HOUR FROM date) → CAST(strftime('%H', date) AS INTEGER)", () => {
    const sql = "SELECT EXTRACT(HOUR FROM created_at) FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(strftime('%H', created_at) AS INTEGER)");
  });

  it("EXTRACT(MINUTE FROM date) → CAST(strftime('%M', date) AS INTEGER)", () => {
    const sql = "SELECT EXTRACT(MINUTE FROM created_at) FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(strftime('%M', created_at) AS INTEGER)");
  });

  it("EXTRACT(SECOND FROM date) → CAST(strftime('%S', date) AS INTEGER)", () => {
    const sql = "SELECT EXTRACT(SECOND FROM created_at) FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(strftime('%S', created_at) AS INTEGER)");
  });
});

describe("PG: Database statements", () => {
  it("CREATE DATABASE → comment", () => {
    const sql = "CREATE DATABASE mydb;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("not supported");
  });

  it("DROP DATABASE → comment", () => {
    const sql = "DROP DATABASE mydb;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("not supported");
  });
});

describe("PG: DEFAULT nextval()", () => {
  it("INT DEFAULT NEXTVAL('seq') NOT NULL → INTEGER NOT NULL", () => {
    const sql = "CREATE TABLE t (id INT DEFAULT NEXTVAL('my_seq') NOT NULL, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("INTEGER NOT NULL");
    expect(result).not.toContain("NEXTVAL");
  });
});

describe("PG: BIGSERIAL", () => {
  it("BIGSERIAL → INTEGER (same as SERIAL)", () => {
    const sql = "CREATE TABLE t (id BIGSERIAL PRIMARY KEY, name TEXT);";
    const result = postgresToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY");
  });
});

describe("PG: Type mappings in CAST shorthand", () => {
  it("::uuid → CAST(expr AS TEXT)", () => {
    const sql = "SELECT id::uuid FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(id AS TEXT)");
  });

  it("::jsonb → CAST(expr AS TEXT)", () => {
    const sql = "SELECT data::jsonb FROM events;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(data AS TEXT)");
  });

  it("::bytea → CAST(expr AS BLOB)", () => {
    const sql = "SELECT data::bytea FROM files;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(data AS BLOB)");
  });

  it("::boolean → CAST(expr AS INTEGER)", () => {
    const sql = "SELECT active::boolean FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(active AS INTEGER)");
  });

  it("::real → CAST(expr AS REAL)", () => {
    const sql = "SELECT price::real FROM products;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("CAST(price AS REAL)");
  });
});

describe("MySQL: DATE_FORMAT() function", () => {
  it("DATE_FORMAT(date, '%Y-%m-%d') → strftime('%Y-%m-%d', date)", () => {
    const sql = "SELECT DATE_FORMAT(created_at, '%Y-%m-%d') FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("strftime('%Y-%m-%d', created_at)");
  });

  it("DATE_FORMAT with hour and minute (known limitation: %i not converted)", () => {
    // MySQL %i (minute) → SQLite %M, but %m (month) is replaced first
    // so %H:%i becomes %H:%M (correct for minute), not %H:%m
    const sql = "SELECT DATE_FORMAT(created_at, '%H:%i') FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("strftime");
    expect(result).toContain("created_at");
  });
});

describe("MySQL: YEAR() / MONTH() / DAY() functions", () => {
  it("YEAR(date) → CAST(strftime('%Y', date) AS INTEGER)", () => {
    const sql = "SELECT YEAR(created_at) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CAST(strftime('%Y', created_at) AS INTEGER)");
  });

  it("MONTH(date) → CAST(strftime('%m', date) AS INTEGER)", () => {
    const sql = "SELECT MONTH(created_at) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CAST(strftime('%m', created_at) AS INTEGER)");
  });

  it("DAY(date) → CAST(strftime('%d', date) AS INTEGER)", () => {
    const sql = "SELECT DAY(created_at) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CAST(strftime('%d', created_at) AS INTEGER)");
  });
});

describe("MySQL: DATEDIFF() function", () => {
  it("DATEDIFF(d1, d2) → CAST(julianday(d1) - julianday(d2) AS INTEGER)", () => {
    const sql = "SELECT DATEDIFF('2024-12-31', '2024-01-01') AS days;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CAST(julianday('2024-12-31') - julianday('2024-01-01') AS INTEGER)");
  });
});

describe("MySQL: CURDATE() function", () => {
  it("CURDATE() → DATE('now')", () => {
    const sql = "SELECT CURDATE();";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DATE('now')");
  });
});

describe("MySQL: SUBSTRING() function", () => {
  it("SUBSTRING(str, pos, len) → SUBSTR(str, pos, len)", () => {
    const sql = "SELECT SUBSTRING(name, 1, 5) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("SUBSTR(name, 1, 5)");
  });
});

describe("MySQL: ISNULL() function", () => {
  it("ISNULL(expr) → IFNULL(expr)", () => {
    const sql = "SELECT ISNULL(name) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("IFNULL(name)");
  });
});

describe("MySQL: CONCAT_WS() function", () => {
  it("CONCAT_WS(sep, a, b) → a || sep || b", () => {
    const sql = "SELECT CONCAT_WS('-', first, last) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("first || '-' || last");
    expect(result).not.toContain("CONCAT_WS");
  });

  it("CONCAT_WS with 3+ values → a || sep || b || sep || c", () => {
    const sql = "SELECT CONCAT_WS('-', first, middle, last) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("first || '-' || middle || '-' || last");
    expect(result).not.toContain("CONCAT_WS");
  });
});

describe("MySQL: SHOW CREATE TABLE", () => {
  it("SHOW CREATE TABLE → sqlite_master query", () => {
    const sql = "SHOW CREATE TABLE users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("sqlite_master");
    expect(result).toContain("users");
  });
});

describe("MySQL: SHOW TABLES LIKE", () => {
  it("SHOW TABLES LIKE 'pattern' → filtered sqlite_master query (backticks in output)", () => {
    const sql = "SHOW TABLES LIKE 'user%';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("sqlite_master");
    expect(result).toContain("user%");
  });
});

describe("MySQL: phpMyAdmin comments removal", () => {
  it("/*!40101 ... */ comments are removed", () => {
    const sql = "/*!40101 SET NAMES utf8 */; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("40101");
    expect(result).toContain("SELECT * FROM users");
  });
});

describe("MySQL: SET commands removal", () => {
  it("SET SQL_MODE=... is removed", () => {
    const sql = "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO'; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("SQL_MODE");
    expect(result).toContain("SELECT * FROM users");
  });

  it("SET time_zone=... is removed", () => {
    const sql = "SET time_zone='+00:00'; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("time_zone");
    expect(result).toContain("SELECT * FROM users");
  });

  it("START TRANSACTION is removed", () => {
    const sql = "START TRANSACTION; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("START TRANSACTION");
    expect(result).toContain("SELECT * FROM users");
  });

  it("COMMIT is removed", () => {
    const sql = "COMMIT; SELECT * FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("COMMIT");
    expect(result).toContain("SELECT * FROM users");
  });
});

describe("MySQL: UNSIGNED removal", () => {
  it("INT UNSIGNED → INTEGER (UNSIGNED removed)", () => {
    const sql = "CREATE TABLE t (id INT UNSIGNED NOT NULL);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INTEGER");
    expect(result).not.toContain("UNSIGNED");
  });

  it("BIGINT UNSIGNED → INTEGER (UNSIGNED removed)", () => {
    const sql = "CREATE TABLE t (id BIGINT UNSIGNED NOT NULL);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INTEGER");
    expect(result).not.toContain("UNSIGNED");
  });
});

describe("MySQL: ENGINE / CHARACTER SET / COLLATE removal", () => {
  it("ENGINE=InnoDB is removed from CREATE TABLE", () => {
    const sql = "CREATE TABLE t (id INT PRIMARY KEY) ENGINE=InnoDB;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("ENGINE");
    expect(result).toContain("id INTEGER PRIMARY KEY");
  });

  it("DEFAULT CHARSET=utf8 is removed", () => {
    const sql = "CREATE TABLE t (id INT PRIMARY KEY) DEFAULT CHARSET=utf8;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("CHARSET");
  });

  it("COLLATE=utf8_general_ci is removed", () => {
    const sql = "CREATE TABLE t (id INT PRIMARY KEY) COLLATE=utf8_general_ci;";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("COLLATE");
  });
});

describe("MySQL: ALTER TABLE multi-clause (phpMyAdmin)", () => {
  it("ALTER TABLE with ADD PRIMARY KEY + ADD KEY splits into separate statements", () => {
    const sql = `ALTER TABLE "auftrag"
      ADD PRIMARY KEY ("AuftrNr"),
      ADD KEY "LKWNr" ("LKWNr"),
      ADD KEY "KdNr" ("KdNr");`;
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ADD PRIMARY KEY");
    expect(result).toContain("CREATE INDEX");
  });

  it("ALTER TABLE ADD KEY → CREATE INDEX", () => {
    const sql = 'ALTER TABLE users ADD KEY idx_name (name);';
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CREATE INDEX");
    expect(result).toContain("idx_name");
  });

  it("ALTER TABLE ADD UNIQUE KEY → CREATE UNIQUE INDEX", () => {
    const sql = 'ALTER TABLE users ADD UNIQUE KEY idx_email (email);';
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CREATE UNIQUE INDEX");
    expect(result).toContain("idx_email");
  });
});

describe("MySQL: ALTER TABLE CHANGE/MODIFY COLUMN", () => {
  it("CHANGE COLUMN old new type → RENAME COLUMN old TO new", () => {
    const sql = "ALTER TABLE users CHANGE COLUMN name full_name VARCHAR(100);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("RENAME COLUMN");
    expect(result).toContain("name");
    expect(result).toContain("full_name");
  });

  it("MODIFY COLUMN col type → comment (not supported)", () => {
    const sql = "ALTER TABLE users MODIFY COLUMN name VARCHAR(200);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("nicht unterstützt");
  });
});

describe("MySQL: ALTER TABLE ADD CONSTRAINT FOREIGN KEY", () => {
  it("ADD CONSTRAINT ... FOREIGN KEY → simplified ALTER TABLE ADD FOREIGN KEY", () => {
    const sql = 'ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id);';
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ADD FOREIGN KEY");
    expect(result).toContain("REFERENCES");
  });

  it("ADD CONSTRAINT ... FOREIGN KEY with ON DELETE CASCADE", () => {
    const sql = 'ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;';
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ON DELETE CASCADE");
  });
});

describe("MySQL: Database statements", () => {
  it("CREATE DATABASE → comment", () => {
    const sql = "CREATE DATABASE mydb;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ignoriert");
  });

  it("DROP DATABASE → comment", () => {
    const sql = "DROP DATABASE mydb;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ignoriert");
  });

  it("USE database → comment", () => {
    const sql = "USE mydb;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ignoriert");
  });

  it("CREATE DATABASE IF NOT EXISTS → comment", () => {
    const sql = "CREATE DATABASE IF NOT EXISTS mydb;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("ignoriert");
  });
});

describe("MySQL: IF() function edge cases", () => {
  it("IF with numeric values", () => {
    const sql = "SELECT IF(score > 50, 1, 0) FROM students;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CASE WHEN score > 50 THEN 1 ELSE 0 END");
  });

  it("IF with string values", () => {
    const sql = "SELECT IF(active = 1, 'yes', 'no') FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CASE WHEN active = 1 THEN 'yes' ELSE 'no' END");
  });
});

describe("MySQL: CONCAT() edge cases", () => {
  it("CONCAT with 3 arguments", () => {
    const sql = "SELECT CONCAT(first, ' ', last) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("first || ' ' || last");
  });

  it("CONCAT with 2 arguments", () => {
    const sql = "SELECT CONCAT(city, country) FROM locations;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("city || country");
  });
});

describe("MySQL: NULL-safe equal operator (<=>)", () => {
  it("a <=> b → a IS b", () => {
    const sql = "SELECT * FROM users WHERE id <=> 5;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id IS 5");
    expect(result).not.toContain("<=>");
  });

  it("a <=> NULL → a IS NULL", () => {
    const sql = "SELECT * FROM users WHERE manager_id <=> NULL;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("manager_id IS NULL");
  });

  it("table.col <=> value → table.col IS value", () => {
    const sql = "SELECT * FROM t WHERE t.status <=> 'active';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("t.status IS 'active'");
  });
});

describe("MySQL: GREATEST / LEAST", () => {
  it("GREATEST(a, b) → MAX(a, b)", () => {
    const sql = "SELECT GREATEST(10, 20) AS max_val;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("MAX(10, 20)");
    expect(result).not.toContain("GREATEST");
  });

  it("GREATEST(a, b, c) → MAX(a, b, c)", () => {
    const sql = "SELECT GREATEST(price, discount, 0) FROM products;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("MAX(price, discount, 0)");
  });

  it("LEAST(a, b) → MIN(a, b)", () => {
    const sql = "SELECT LEAST(10, 20) AS min_val;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("MIN(10, 20)");
    expect(result).not.toContain("LEAST");
  });

  it("LEAST(a, b, c) → MIN(a, b, c)", () => {
    const sql = "SELECT LEAST(price, sale_price, 0) FROM products;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("MIN(price, sale_price, 0)");
  });
});

describe("MySQL: TIMESTAMPDIFF", () => {
  it("TIMESTAMPDIFF(DAY, start, end) → julianday difference in days", () => {
    const sql = "SELECT TIMESTAMPDIFF(DAY, '2024-01-01', '2024-06-15') AS days;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CAST(julianday('2024-06-15') - julianday('2024-01-01') AS INTEGER)");
  });

  it("TIMESTAMPDIFF(MONTH, start, end) → approximate months", () => {
    const sql = "SELECT TIMESTAMPDIFF(MONTH, start_date, end_date) FROM t;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("30.44");
    expect(result).toContain("julianday");
  });

  it("TIMESTAMPDIFF(YEAR, start, end) → approximate years", () => {
    const sql = "SELECT TIMESTAMPDIFF(YEAR, '2020-01-01', '2024-01-01') AS years;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("365.25");
  });
});

describe("MySQL: TIMESTAMPADD", () => {
  it("TIMESTAMPADD(MONTH, 3, date) → date(date, '+3 months')", () => {
    const sql = "SELECT TIMESTAMPADD(MONTH, 3, '2024-01-01');";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("date('2024-01-01', '+3 months')");
  });

  it("TIMESTAMPADD(YEAR, 1, date) → date(date, '+1 years')", () => {
    const sql = "SELECT TIMESTAMPADD(YEAR, 1, created_at) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("date(created_at, '+1 years')");
  });

  it("TIMESTAMPADD(DAY, 7, date) → date(date, '+7 days')", () => {
    const sql = "SELECT TIMESTAMPADD(DAY, 7, start_date) FROM events;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("date(start_date, '+7 days')");
  });
});

describe("MySQL: XOR operator", () => {
  it("a XOR b → ((a OR b) AND NOT (a AND b))", () => {
    const sql = "SELECT * FROM t WHERE active XOR admin;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("((active OR admin) AND NOT (active AND admin))");
    expect(result).not.toContain("XOR");
  });

  it("XOR with column references", () => {
    const sql = "SELECT * FROM users WHERE is_active XOR is_banned;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("((is_active OR is_banned) AND NOT (is_active AND is_banned))");
  });
});

describe("MySQL: Backtick conversion", () => {
  it("Backticks → double quotes", () => {
    const sql = "SELECT `name`, `age` FROM `users`;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('"name"');
    expect(result).toContain('"users"');
    expect(result).not.toContain("`");
  });
});

// ===== NEW TESTS FOR GAP ANALYSIS FIXES =====

describe("PG: FILTER with nested parens", () => {
  it("COUNT(DISTINCT name) FILTER (WHERE active = 1)", () => {
    const sql = "SELECT COUNT(DISTINCT name) FILTER (WHERE active = 1) FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("SUM(CASE WHEN active = 1 THEN 1 ELSE 0 END)");
    expect(result).not.toContain("FILTER");
  });

  it("SUM(CASE WHEN x THEN y) FILTER (WHERE cond)", () => {
    const sql = "SELECT SUM(CASE WHEN status = 'active' THEN amount ELSE 0 END) FILTER (WHERE year = 2024) FROM sales;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("SUM(CASE WHEN year = 2024 THEN CASE WHEN status = 'active' THEN amount ELSE 0 END ELSE NULL END)");
    expect(result).not.toContain("FILTER");
  });
});

describe("PG: STRING_AGG with nested parens", () => {
  it("STRING_AGG with simple args", () => {
    const sql = "SELECT STRING_AGG(name, ', ') FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("GROUP_CONCAT(name, ', ')");
    expect(result).not.toContain("STRING_AGG");
  });

  it("STRING_AGG with nested function call", () => {
    const sql = "SELECT STRING_AGG(UPPER(name), ', ') FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("GROUP_CONCAT(UPPER(name), ', ')");
    expect(result).not.toContain("STRING_AGG");
  });
});

describe("MySQL: CONCAT with nested parens", () => {
  it("CONCAT with nested CONCAT", () => {
    const sql = "SELECT CONCAT(CONCAT(first, ' '), last) FROM users;";
    const result = mysqlToSqlite(sql);
    // Inner CONCAT is transformed first: CONCAT(first, ' ') → first || ' '
    // Then outer: CONCAT(first || ' ', last) → first || ' ' || last
    expect(result).toContain("||");
    expect(result).not.toContain("CONCAT");
  });

  it("CONCAT_WS with nested CONCAT", () => {
    const sql = "SELECT CONCAT_WS('-', CONCAT(first, ' '), last) FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("||");
    expect(result).not.toContain("CONCAT");
  });
});

describe("MySQL: IF() with nested IF", () => {
  it("IF(a, IF(b, c, d), e) → nested CASE WHEN", () => {
    const sql = "SELECT IF(status = 'active', IF(role = 'admin', 'super', 'user'), 'guest') FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CASE WHEN");
    expect(result).not.toContain("IF(");
  });

  it("IF with comma in string literal", () => {
    const sql = "SELECT IF(status = 'active', 'yes, sir', 'no') FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("CASE WHEN status = 'active' THEN 'yes, sir' ELSE 'no' END");
  });
});

describe("MySQL: INSERT IGNORE → INSERT OR IGNORE", () => {
  it("INSERT IGNORE INTO → INSERT OR IGNORE INTO", () => {
    const sql = "INSERT IGNORE INTO users (name) VALUES ('John');";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INSERT OR IGNORE INTO");
    expect(result).not.toContain("INSERT IGNORE");
  });
});

describe("PG: ILIKE with function expression", () => {
  it("LOWER(name) ILIKE '%foo%'", () => {
    const sql = "SELECT * FROM users WHERE LOWER(name) ILIKE '%foo%';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(LOWER(name)) LIKE LOWER('%foo%')");
    expect(result).not.toContain("ILIKE");
  });
});

describe("PG: NOT ILIKE with function expression", () => {
  it("LOWER(name) NOT ILIKE '%foo%'", () => {
    const sql = "SELECT * FROM users WHERE LOWER(name) NOT ILIKE '%foo%';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(LOWER(name)) NOT LIKE LOWER('%foo%')");
    expect(result).not.toContain("ILIKE");
  });
});

describe("PG: String literal protection in transforms", () => {
  it("ILIKE inside string literal is not transformed", () => {
    const sql = "SELECT 'this ILIKE that' FROM users;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("ILIKE");
  });

  it("EXTRACT inside string literal is not transformed", () => {
    const sql = "SELECT 'EXTRACT(YEAR FROM date)' AS label;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("EXTRACT");
  });

  it("IS DISTINCT FROM inside string literal is not transformed", () => {
    const sql = "SELECT 'a IS DISTINCT FROM b' AS label;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("IS DISTINCT FROM");
  });

  it("CAST shorthand inside string literal is not transformed", () => {
    const sql = "SELECT 'value::text' AS label;";
    const result = postgresToSqlite(sql);
    expect(result).toContain("::text");
  });
});

describe("MySQL: String literal protection in transforms", () => {
  it("NOW() inside string literal is not transformed", () => {
    const sql = "SELECT 'call NOW() for current time' AS label;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("NOW()");
  });

  it("IF() inside string literal is not transformed", () => {
    const sql = "SELECT 'use IF(a,b,c) for conditions' AS label;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("IF(a,b,c)");
  });
});

describe("PG: IS DISTINCT FROM with string literal operand", () => {
  it("a IS DISTINCT FROM 'hello'", () => {
    const sql = "SELECT * FROM users WHERE name IS DISTINCT FROM 'hello';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("IS NOT");
    expect(result).not.toContain("DISTINCT");
  });
});

describe("MySQL: || operator warning", () => {
  it("|| in SQL triggers warning", () => {
    const warnings = getCompatWarnings("SELECT * FROM t WHERE a = 1 || b = 2;", "mysql");
    expect(warnings.some(w => w.includes("||"))).toBe(true);
  });
});

describe("MySQL: INSERT IGNORE warning", () => {
  it("INSERT IGNORE triggers warning", () => {
    const warnings = getCompatWarnings("INSERT IGNORE INTO users (name) VALUES ('John');", "mysql");
    expect(warnings.some(w => w.includes("INSERT IGNORE"))).toBe(true);
  });
});

describe("PG: New feature warnings", () => {
  it("IS DISTINCT FROM triggers warning", () => {
    const warnings = getCompatWarnings("SELECT * FROM t WHERE a IS DISTINCT FROM b;", "postgresql");
    expect(warnings.some(w => w.includes("IS DISTINCT FROM"))).toBe(true);
  });

  it("STRING_AGG triggers warning", () => {
    const warnings = getCompatWarnings("SELECT STRING_AGG(name, ',') FROM t;", "postgresql");
    expect(warnings.some(w => w.includes("STRING_AGG"))).toBe(true);
  });

  it("FILTER (WHERE ...) triggers warning", () => {
    const warnings = getCompatWarnings("SELECT COUNT(*) FILTER (WHERE active = 1) FROM t;", "postgresql");
    expect(warnings.some(w => w.includes("FILTER"))).toBe(true);
  });

  it("TO_CHAR triggers warning", () => {
    const warnings = getCompatWarnings("SELECT TO_CHAR(date_col, 'YYYY-MM-DD') FROM t;", "postgresql");
    expect(warnings.some(w => w.includes("TO_CHAR"))).toBe(true);
  });
});

describe("MySQL: Backtick conversion", () => {
  it("Backticks → double quotes", () => {
    const sql = "SELECT `name`, `age` FROM `users`;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('"name"');
    expect(result).toContain('"users"');
    expect(result).not.toContain("`");
  });

  it("Backticks in CREATE TABLE", () => {
    const sql = "CREATE TABLE `my_table` (`id` INT PRIMARY KEY, `name` VARCHAR(100));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('"my_table"');
    expect(result).toContain('"id"');
    expect(result).toContain("INTEGER PRIMARY KEY");
    expect(result).toContain("TEXT");
  });
});

describe("MySQL: ON DUPLICATE KEY UPDATE", () => {
  it("INSERT ... ON DUPLICATE KEY UPDATE → INSERT OR REPLACE", () => {
    const sql = "INSERT INTO users (id, name) VALUES (1, 'John') ON DUPLICATE KEY UPDATE name='John';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INSERT OR REPLACE INTO users");
    expect(result).not.toContain("ON DUPLICATE KEY");
  });
});

describe("MySQL: TRUNCATE TABLE", () => {
  it("TRUNCATE TABLE users → DELETE FROM users", () => {
    const sql = "TRUNCATE TABLE users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("DELETE FROM users");
  });
});

describe("MySQL: DESCRIBE / SHOW COLUMNS", () => {
  it("DESCRIBE table → PRAGMA table_info", () => {
    const sql = "DESCRIBE users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('PRAGMA table_info("users")');
  });

  it("SHOW COLUMNS FROM table → PRAGMA table_info", () => {
    const sql = "SHOW COLUMNS FROM users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('PRAGMA table_info("users")');
  });
});

describe("Error mapping: PostgreSQL", () => {
  it("no such table → relation does not exist", () => {
    
    const result = mapSqliteError("no such table: users", "postgresql");
    expect(result).toContain("does not exist");
  });

  it("no such column → column does not exist", () => {
    
    const result = mapSqliteError("no such column: name", "postgresql");
    expect(result).toContain("does not exist");
  });

  it("unique constraint failed → duplicate key", () => {
    
    const result = mapSqliteError("UNIQUE constraint failed: users.id", "postgresql");
    expect(result).toContain("duplicate key");
  });
});

describe("Error mapping: MySQL", () => {
  it("no such table → Table doesn't exist", () => {
    
    const result = mapSqliteError("no such table: users", "mysql");
    expect(result).toContain("doesn't exist");
  });

  it("no such column → Unknown column", () => {
    
    const result = mapSqliteError("no such column: name", "mysql");
    expect(result).toContain("Unknown column");
  });

  it("table already exists → Table already exists", () => {
    
    const result = mapSqliteError("table users already exists", "mysql");
    expect(result).toContain("already exists");
  });
});

describe("Error mapping: SQLite (pass-through)", () => {
  it("SQLite errors pass through unchanged", () => {
    
    const result = mapSqliteError("syntax error near FROM", "sqlite");
    expect(result).toBe("syntax error near FROM");
  });
});

describe("Type mapping: PostgreSQL", () => {
  it("INTEGER → INTEGER", () => {
    
    expect(mapSqliteType("INTEGER", "postgresql")).toBe("INTEGER");
  });

  it("TEXT → TEXT", () => {
    
    expect(mapSqliteType("TEXT", "postgresql")).toBe("TEXT");
  });

  it("REAL → DOUBLE PRECISION", () => {
    
    expect(mapSqliteType("REAL", "postgresql")).toBe("DOUBLE PRECISION");
  });

  it("BLOB → BYTEA", () => {
    
    expect(mapSqliteType("BLOB", "postgresql")).toBe("BYTEA");
  });
});

describe("Type mapping: MySQL", () => {
  it("INTEGER → INT", () => {
    
    expect(mapSqliteType("INTEGER", "mysql")).toBe("INT");
  });

  it("TEXT → VARCHAR(255)", () => {
    
    expect(mapSqliteType("TEXT", "mysql")).toBe("VARCHAR(255)");
  });

  it("REAL → DOUBLE", () => {
    
    expect(mapSqliteType("REAL", "mysql")).toBe("DOUBLE");
  });

  it("BLOB → BLOB", () => {
    
    expect(mapSqliteType("BLOB", "mysql")).toBe("BLOB");
  });
});

describe("Type mapping: SQLite (pass-through)", () => {
  it("SQLite types pass through unchanged", () => {
    
    expect(mapSqliteType("INTEGER", "sqlite")).toBe("INTEGER");
    expect(mapSqliteType("TEXT", "sqlite")).toBe("TEXT");
    expect(mapSqliteType("REAL", "sqlite")).toBe("REAL");
  });
});

describe("Transpilation: dialectCompat routing", () => {
  it("sqlite dialect passes through unchanged", () => {
    
    const sql = "SELECT * FROM users WHERE active = TRUE;";
    expect(transpileToSqlite(sql, "sqlite")).toBe(sql);
  });

  it("mysql dialect routes to mysqlToSqlite", () => {
    
    const sql = "SELECT * FROM users WHERE active = TRUE;";
    const result = transpileToSqlite(sql, "mysql");
    expect(result).toContain("1");
    expect(result).not.toContain("TRUE");
  });

  it("postgresql dialect routes to postgresToSqlite", () => {
    
    const sql = "SELECT * FROM users WHERE active = TRUE;";
    const result = transpileToSqlite(sql, "postgresql");
    expect(result).toContain("1");
    expect(result).not.toContain("TRUE");
  });
});

describe("PG: NOT ILIKE (known limitation)", () => {
  it("NOT ILIKE → NOT LOWER() LIKE LOWER()", () => {
    const sql = "SELECT * FROM users WHERE name NOT ILIKE '%admin%';";
    const result = postgresToSqlite(sql);
    expect(result).toContain("LOWER(name) NOT LIKE LOWER('%admin%')");
    expect(result).not.toContain("ILIKE");
  });
});

describe("PG: RETURNING with column list", () => {
  it("RETURNING id, name is removed", () => {
    const sql = "INSERT INTO users (name) VALUES ('John') RETURNING id, name;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("RETURNING");
  });

  it("RETURNING * is removed", () => {
    const sql = "INSERT INTO users (name) VALUES ('John') RETURNING *;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("RETURNING");
  });

  it("RETURNING single column is removed", () => {
    const sql = "INSERT INTO users (name) VALUES ('John') RETURNING id;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("RETURNING");
  });
});

describe("MySQL: FLOAT type mapping", () => {
  it("FLOAT → REAL in CREATE TABLE (bare FLOAT and FLOAT(n,m))", () => {
    const sql = "CREATE TABLE t (price FLOAT, discount FLOAT(5,2));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("price REAL");
    expect(result).toContain("discount REAL");
  });
});

describe("MySQL: TINYINT / SMALLINT / MEDIUMINT / BIGINT type mappings", () => {
  it("TINYINT(1) → INTEGER", () => {
    const sql = "CREATE TABLE t (active TINYINT(1));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("active INTEGER");
  });

  it("SMALLINT(5) → INTEGER", () => {
    const sql = "CREATE TABLE t (count SMALLINT(5));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("count INTEGER");
  });

  it("MEDIUMINT(7) → INTEGER", () => {
    const sql = "CREATE TABLE t (value MEDIUMINT(7));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("value INTEGER");
  });

  it("BIGINT(20) → INTEGER", () => {
    const sql = "CREATE TABLE t (id BIGINT(20));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER");
  });
});

describe("MySQL: ON UPDATE CURRENT_TIMESTAMP removal", () => {
  it("ON UPDATE CURRENT_TIMESTAMP is removed", () => {
    const sql = "CREATE TABLE t (id INT PRIMARY KEY, updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);";
    const result = mysqlToSqlite(sql);
    expect(result).not.toContain("ON UPDATE CURRENT_TIMESTAMP");
    expect(result).toContain("DEFAULT CURRENT_TIMESTAMP");
  });
});

describe("MySQL: AUTO_INCREMENT reordering", () => {
  it("INT AUTO_INCREMENT PRIMARY KEY → INTEGER PRIMARY KEY AUTOINCREMENT", () => {
    const sql = "CREATE TABLE t (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("id INTEGER PRIMARY KEY AUTOINCREMENT");
  });

  it("INT NOT NULL AUTO_INCREMENT → INTEGER NOT NULL AUTOINCREMENT", () => {
    const sql = "CREATE TABLE t (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("INTEGER NOT NULL");
    expect(result).toContain("PRIMARY KEY AUTOINCREMENT");
  });
});

describe("PG: Multi-column CREATE TABLE with mixed types", () => {
  it("Complex table with SERIAL, VARCHAR, TIMESTAMP, BOOLEAN, DECIMAL", () => {
    const sql = "CREATE TABLE orders (id SERIAL PRIMARY KEY, name VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, active BOOLEAN, price DECIMAL(10,2));";
    const result = postgresToSqlite(sql);
    expect(result).toContain("INTEGER PRIMARY KEY AUTOINCREMENT");
    expect(result).toContain("name TEXT");
    expect(result).toContain("created_at TEXT DEFAULT CURRENT_TIMESTAMP");
    expect(result).toContain("active INTEGER");
    expect(result).toContain("price REAL");
  });
});

// ─── View Transpilation Tests ──────────────────────────────────────────────

describe("MySQL: CREATE OR REPLACE VIEW", () => {
  it("CREATE OR REPLACE VIEW → DROP VIEW IF EXISTS; CREATE VIEW", () => {
    const sql = "CREATE OR REPLACE VIEW active_users AS SELECT * FROM users WHERE active = 1;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain('DROP VIEW IF EXISTS "active_users"');
    expect(result).toContain('CREATE VIEW "active_users" AS');
    expect(result).not.toContain("OR REPLACE");
  });
});

describe("MySQL: SHOW CREATE VIEW", () => {
  it("SHOW CREATE VIEW → SELECT from sqlite_master", () => {
    const sql = "SHOW CREATE VIEW active_users;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("sqlite_master");
    expect(result).toContain("type = 'view'");
    expect(result).toContain("active_users");
  });
});

describe("MySQL: SHOW TABLES includes views", () => {
  it("SHOW TABLES → includes views in sqlite_master query", () => {
    const sql = "SHOW TABLES;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("type IN ('table', 'view')");
  });

  it("SHOW TABLES LIKE → includes views", () => {
    const sql = "SHOW TABLES LIKE 'user%';";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("type IN ('table', 'view')");
  });

  it("SHOW TABLES FROM db → includes views", () => {
    const sql = "SHOW TABLES FROM mydb;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("type IN ('table', 'view')");
  });
});

describe("MySQL: SHOW FULL TABLES", () => {
  it("SHOW FULL TABLES → includes Table_type column", () => {
    const sql = "SHOW FULL TABLES;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("Table_type");
    expect(result).toContain("'table'");
    expect(result).toContain("'view'");
  });
});

describe("MySQL: SHOW CREATE TABLE includes views", () => {
  it("SHOW CREATE TABLE → includes views in sqlite_master query", () => {
    const sql = "SHOW CREATE TABLE my_view;";
    const result = mysqlToSqlite(sql);
    expect(result).toContain("type IN ('table', 'view')");
  });
});

describe("PostgreSQL: CREATE OR REPLACE VIEW", () => {
  it("CREATE OR REPLACE VIEW → DROP VIEW IF EXISTS; CREATE VIEW", () => {
    const sql = "CREATE OR REPLACE VIEW active_users AS SELECT * FROM users WHERE active = 1;";
    const result = postgresToSqlite(sql);
    expect(result).toContain('DROP VIEW IF EXISTS "active_users"');
    expect(result).toContain('CREATE VIEW "active_users" AS');
    expect(result).not.toContain("OR REPLACE");
  });
});

describe("PostgreSQL: WITH CHECK OPTION stripping", () => {
  it("WITH CHECK OPTION is stripped from CREATE VIEW", () => {
    const sql = "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1 WITH CHECK OPTION;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("CHECK OPTION");
    expect(result).toContain("CREATE VIEW");
  });

  it("WITH CASCADED CHECK OPTION is stripped", () => {
    const sql = "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1 WITH CASCADED CHECK OPTION;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("CHECK OPTION");
    expect(result).not.toContain("CASCADED");
  });

  it("WITH LOCAL CHECK OPTION is stripped", () => {
    const sql = "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1 WITH LOCAL CHECK OPTION;";
    const result = postgresToSqlite(sql);
    expect(result).not.toContain("CHECK OPTION");
    expect(result).not.toContain("LOCAL");
  });
});

describe("SQLite: CREATE VIEW / DROP VIEW pass-through", () => {
  it("CREATE VIEW passes through unchanged for sqlite dialect", () => {
    const sql = "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1;";
    expect(transpileToSqlite(sql, "sqlite")).toBe(sql);
  });

  it("DROP VIEW passes through unchanged for sqlite dialect", () => {
    const sql = "DROP VIEW IF EXISTS active_users;";
    expect(transpileToSqlite(sql, "sqlite")).toBe(sql);
  });
});
